---
- name: Start SAS Viya Instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-057fc79a3326922e5'
      - 'i-0400d97509290e60e'
    region: us-east-1
  tasks:
    - name: Starting instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True

