---

- hosts: all
  become: true
  become_user: root

  ## read in the vars file from the normal playbook
  vars_files:
    - viya_log_gather_vars.yml
  tasks:

    - name: find all log files that have changed in the timeperiod
      find:
        paths: "{{ log_dir }}"
        recurse: yes
        age: "{{ timeperiod }}"
        patterns: "{{ services }}"
      register: files_to_copy

    - debug: var=files_to_copy

    - shell: hostname
      register: fromhost

    - local_action: shell date +%Y-%m-%d-%H_%M_%S
      register: ctimestamp


    - name: collect log files to ansible machine
      fetch:
        src: "{{ item.path }}"
        dest: "{{  collect_dir + 'D' + ctimestamp.stdout + '/' + fromhost.stdout  + '/' }}"
        flat: yes
      with_items: "{{ files_to_copy.files }}"


    - name: search log files for specific string
      local_action: shell  grep {{ search_string }} -B 2 -A 2  {{ collect_dir }}D{{ ctimestamp.stdout }}/*/*.log
      register: log_errors

    - debug: var=log_errors



    - name: save search results to a file
      local_action: copy content={{ log_errors.stdout }} dest="{{  collect_dir + 'D' + ctimestamp.stdout + '/logged_info.txt' }}"
