#!/bin/sh

UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINUTES=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)

cat << EOF
 %                                                                            %
 %+++++++++++++++++++++++++++++++ SERVER INFO ++++++++++++++++++++++++++++++++%
 %                                                                            %
      Name: `hostname -f`
      Uptime: $UPTIME_DAYS days, $UPTIME_HOURS hours, $UPTIME_MINUTES minutes

      CPU: `cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2`
         Load: `cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3}'`
      Memory: `free -m | head -n 2 | tail -n 1 | awk {'print $2'}`M
      Disk: `df -h / | awk '{ a = $2 } END { print a }'`
      Distro: `cat /proc/version`

EOF
